### ISSUE TITLE
docsy prep work

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#126]
- [x] Add docsy module from [cncf/docsy] repo, pinned to the [etcd.io branch]. @chalin --> #125
- [x] Merge #124 and #125 in that order. @nate-double-u 
- [x] Create a branch named `docsy`. This is the branch against which we'll be creating docsy-related PRs.  @nate-double-u
- [x] Update the Netlify config so that previews are automatically built for the `docsy` branch. https://github.com/etcd-io/website/issues/127 https://github.com/etcd-io/website/pull/128 @nate-double-u
- [x] Create a `docsy` label so that we can tag docsy-specific issues and PRs. @nate-double-u

**Suggested process** for working with the `docsy` branch:

- We can now implement the Docsy conversion (#94) incrementally by submitting commits and PRs over the `docsy` branch.
  - Issues and PRs for the `docsy` branch should be tagged with the `docsy` label and/or have their title prefixed with `[docsy]`
- IMPORTANT: when accepting PRs over the `docsy` branch, use **Squash and merge**
- IMPORTANT: when updating the `docsy` branch relative to `master`, do a **rebase** not a merge.
  - Ideally, such a rebase should only be done when there are no PRs open over `docsy`
   
Also:

- Ensure that a production deploy of the docsy branch, once we reach that point, is indexable by search engines.

[cncf/docsy]: https://github.com/cncf/docsy
[etcd.io branch]: https://github.com/cncf/docsy/tree/etcd.io

**Comment by chalin** [comment]
@nate-double-u: maybe we can move/copy the "suggested process" to #94 and close this issue?

**Comment by nate-double-u** [comment]
> @nate-double-u: maybe we can move/copy the "suggested process" to #94 and close this issue?

Do you have access to edit #94?

**Comment by chalin** [comment]
> Do you have access to edit #94?

No 😞

**Comment by nate-double-u** [comment]
Closing in favour of https://github.com/etcd-io/website/issues/134
