### ISSUE TITLE
Convert to Docsy theme

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#134]
Supersedes #94, #126

As per the [conversation](https://github.com/etcd-io/website/issues/65#issuecomment-756393360) around the [Etcd.io Docs/SEO Improvement Plan](https://github.com/etcd-io/website/issues/65):

- [x] Plan docsy migration https://github.com/etcd-io/website/issues/126
  - [x] Is Docsy migration still warranted? (after some cleanup and migration of docs to the website, is it still the best option? What about Docusaurus?)

---
# Initial docsy conversion

- [x] Generate site using the [Docsy Example site](https://github.com/google/docsy-example/) #112
- [x] Pull in Documentation as is #112
  - [x] Move Documentation to `content/en` folder #112
  - [x] Ensure no links/bookmarks are broken in the conversion process
- [x] Ensure front page content created is the same as the original page #112
  - [x] Page structure allows for upcoming changes as per the [new information architecture](https://github.com/etcd-io/website/issues/110)
- [x] Ensure site builds #112
  - [x] locally (`make serve`, using hugo serve)
  - [x] locally (`docker-compose up --build`)
  - [x] netlify
- [x] update README #144
- [x] Ensure that existing functionality is not lost
  - [x] Versions
    - [x] Add warnings to DRAFT and DEPRECATED pages #236
  - [x] Apply empty href fix to docsy branch (see: https://github.com/etcd-io/website/issues/180) https://github.com/etcd-io/website/issues/198
- [x] Prepare for internationalization
  - [x] Bring in language safe version selector from [PoC](https://github.com/nate-double-u/docsy-example/blob/6a22637b66833c9e13f85b66001d731badb3d8e1/layouts/partials/navbar-version-selector.html#L1) https://github.com/etcd-io/website/issues/135 #112
  - [x] Ensure versioning system works with i10n system
    Proof of concept work here shows an older rev of our versioning system working with languages: https://deploy-preview-1--jolly-albattani-baa029.netlify.app/
https://deploy-preview-1--jolly-albattani-baa029.netlify.app/docs/current/ <-- English
https://deploy-preview-1--jolly-albattani-baa029.netlify.app/no/docs/current/ <-- Norsk

Min items before initial merge ([milestone](https://github.com/etcd-io/website/milestone/2)):

- [x] Ensure the homepage looks like (or better than) the original homepage #215
- [x] Footer: the "user" and "developer" links should refer to etcd resources #228
- [x] (Minor) Also use the compact section listing format for the "Next docs" page #231
- [x] Add etcd favicon #232
- [x] Create a custom 404 page #238

Post-docsy conversion ([milestone](https://github.com/etcd-io/website/milestone/3)):

- [ ] Ensure that the branch name in the config file is switched back to master
- [x] (Minor) Fix broken internal links: latest https://github.com/etcd-io/website/pull/227
- [ ] Versions menu shouldn't take up real estate in the top nav if it isn't being shown
- [ ] Consider reintroducing page descriptions on version landing pages as part of IA discussion
- [ ] Automatic page generation is preserved (see https://github.com/etcd-io/website/issues/111 & https://github.com/etcd-io/etcd/issues/12768)
- [x] List of generated metrics files (as per conversation https://github.com/etcd-io/website/pull/171#issuecomment-810533295) https://github.com/etcd-io/website/pull/242
- [ ] Clean out any unused assets, layouts, etc from the pre-docsy version of the site
- [ ] Footer: copyright date range should match license file
- [ ] Check if we still need specific files after initial docsy-conversion #139
- [x] Setup Blog URL Permalinks #140
- [ ] Ensure that author names appear in blog entries

---

# prep work

- [x] Create a `docsy` branch
  - [x] Add docsy submodule https://github.com/etcd-io/website/pull/125
  - [x] Consider: Move site pages into `content/en` #112

# Cleanup

- [x] Ensure that only the docs for actively selected version show up in the side-nav #135
- [x] Footer: streamline and bring closer to updated CNCF website  guidelines #137 #207
- [x] Use a Netlify _redirects file to hold redirects #138

---

**Suggested process** for working with the `docsy` branch:

- We can now implement the Docsy conversion (#94) incrementally by submitting commits and PRs over the `docsy` branch.
  - Issues and PRs for the `docsy` branch should be tagged with the `docsy` label and/or have their title prefixed with `[docsy]`
- IMPORTANT: when accepting PRs over the `docsy` branch, use **Squash and merge**
- IMPORTANT: when updating the `docsy` branch relative to `master`, do a **rebase** not a merge.
  - Ideally, such a rebase should only be done when there are no PRs open over `docsy`
   
Also:

- Ensure that a production deploy of the docsy branch, once we reach that point, is indexable by search engines.

[cncf/docsy]: https://github.com/cncf/docsy
[etcd.io branch]: https://github.com/cncf/docsy/tree/etcd.io

**Comment by nate-double-u** [comment]
We may want to break this issue into a new docsy followup issue. The initial work is done, and anything that is unchecked in the description above still needs to be done, will be done outside of an 'initial' setup.

**Comment by chalin** [comment]
That works for me.

**Comment by nate-double-u** [comment]
> That works for me.

I'll leave the issue creation to you @chalin (so you're able to edit it...)

**Comment by chalin** [comment]
Right, thanks!

**Comment by chalin** [comment]
Actually, I'd vote to continue using this issue for a while longer. (Maybe we can discuss over Slack)

**Comment by nate-double-u** [comment]
After all the work around issue https://github.com/etcd-io/website/issues/152, I've rebased `docsy` onto `master` (have I got that phrase the right way around?) and it is building with the new docs version structure.

Deploy preview: https://605d1e5922cf8800084788f8--etcd.netlify.app/

**Comment by nate-double-u** [comment]
If we're keeping this issue open for a while, cc'ing folks for visibility :)
/cc @zacharysarah, @spzala, @jberkus

**Comment by nate-double-u** [comment]
I've rebased `docsy` onto `master`.

Deploy preview: https://605e481068d09100070658d6--etcd.netlify.app/

(Let me know if these rebase updates aren't helpful. I' m sharing mostly as a heads up that it's been done, and that it has built successfully. As it's a branch and not a PR, i'm not sure quite how else to share this info.)

**Comment by nate-double-u** [comment]
Is this, https://github.com/google/docsy-example/pull/112#pullrequestreview-624867681, something we should consider for our docker image setup as well? I like the idea of not having to update it, but I also like the idea of keeping the version in lockstep with the Netlify version.

**Comment by nate-double-u** [comment]
I've rebased `docsy` onto `master`.

Deploy preview: https://606ce0b4a13d70000809d224--etcd.netlify.app/

**Comment by nate-double-u** [comment]
I've rebased `docsy` onto `master`

Deploy preview: https://606e25ee56bfce0007e1c9b0--etcd.netlify.app/

**Comment by nate-double-u** [comment]
I've rebased `docsy` onto `master`

Deploy preview: https://606e25ee56bfce0007e1c9b0--etcd.netlify.app/

**Comment by nate-double-u** [comment]
Rebasing `docsy` onto `master` after PR #207 

Deploy preview: https://60708701f5bfe20007fa11c3--etcd.netlify.app/

**Comment by nate-double-u** [comment]
Rebasing `docsy` onto `master`.

Deploy preview: https://6074b7548852d300089f3fc8--etcd.netlify.app/

**Comment by nate-double-u** [comment]
Rebasing `docsy` onto `master`.

Deploy preview: https://6074cff477df2000077d4676--etcd.netlify.app/

**Comment by nate-double-u** [comment]
Rebaseing `docsy` onto `master`.

Deploy preview: https://6075cced8fc5150008dfe917--etcd.netlify.app/

**Comment by nate-double-u** [comment]
Rebasing `docsy` onto `master`.

Deploy preview: https://607883c23903f00008a0377b--etcd.netlify.app/

**Comment by nate-double-u** [comment]
@chalin could you open a `Post-docsy conversion` issue based on the _Post-docsy conversion_ section of this issue's description so we continue to have a tracking issue for the remaining docsy work? 

Or would you prefer:
1. to just use the Milestone system to track that remaining work
2. to reopen this issue
3. other

**Comment by chalin** [comment]
Done: #247
