### ISSUE TITLE
config: ignoreFiles entries are invalid

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#189]
The `config` file `ignoreFiles` entries are invalid. Here they are:

https://github.com/etcd-io/website/blob/40f9d7b01722519926945ec8df05b23af57f7509/config.toml#L8-L12

AFAICT from the [Ignore Content and Data Files when Rendering](https://gohugo.io/getting-started/configuration/#ignore-content-and-data-files-when-rendering), regex entries are already relative to `content` and `data` and so shouldn't start with either of these prefixes.

The invalid regex rules would explain why they aren't working :). That is, for the past two years the site has been publishing certain files that were meant to be excluded. For example, **lock example** readme and source files are being published as reported via #188.

Rather than fix the regex rules, I suggest either eliminating the files that are being ignore (which is what is being suggested for #188), or properly integrating the files into the website (reworking file content if necessary).

- [x] Remove `ignoreFiles` from the config - #190
- [x] Address files matched by:
  - [x]  `content/docs/v*/*/README.md` - #188
  - [x] `content/docs/v*/docs.md` - #190
  - [x] `content/docs/v3.4.0/etcd-mixin` - #187

**Comment by chalin** [comment]
All done.
