### ISSUE TITLE
Install page: create from reworked download-and-build

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#318]
Part of _New IA implementation_ #267:

- [x] `/docs/next/`:
  - [x] **Install** page from reworked `dl-build` page - #294, #323
  - [x] Rename file and add redirect rule - #319
- [ ] `/docs/v3.4/`, i.e., `/docs/latest`: #333 
  - [ ] **Install** page from reworked `dl-build` page
  - [ ] Rename file and add redirect rule
  - [ ] Add **Install** link to top-nav
- [ ] All other versions: #333
  - [ ] Rename all `dl-build` pages to `install`, so that the versions menu will work more smoothly
  - [ ] Change page titles to be **Install**
  - [ ] Add redirect rules
