### ISSUE TITLE
v3.5 Documentation

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#328]
This issue collects the documentation activities that need to be done to support the [v3.5](https://github.com/etcd-io/etcd/issues/12970) docs.

Docs release:

- [x] Create v3.5 docs from `/docs/next`. Two options: either rename `next` to `v3.5` (as suggested in the comment below), or copy it (not @chalin's preferred choice)
- [x] Ensure `latest` refers to v3.5 #379
- [x] Decide what `next` will refer to - for now, v3.5 (NW) #379
- [x] Change v3.5-DRAFT to v3.5 #377
- [x] Update `git_version_tag` in v3.5 _index.md front-matter #379

Additions (v3.5-specific):

- [x] Blog post announcing the release - #312, #331, #376, #379
  (set draft status to false and set correct date)
- [x] Add initial docs for experimental distributed tracing feature https://github.com/etcd-io/website/issues/280, #373
- [ ] Add etcdutl documentation https://github.com/etcd-io/website/issues/309

Updates (v3.5-specific):

- [x] Update API reference docs (`/content/en/docs/next/dev-guide/`: `api_concurrency_reference_v3.md` & `api_reference_v3.md`) using [`etcd-io/etcd/scripts/genproto.sh`](https://github.com/etcd-io/etcd/blob/main/scripts/genproto.sh). https://github.com/etcd-io/etcd/issues/13080.  #380

Related issues: #322 (which contains a long list to other related issues).

**Comment by chalin** [comment]
I'd like to propose the following strategy, at least until we decide whether #252 will be addressed or not:

 1. Rename `/docs/next` to `/docs/v3.5`
 2. Add a redirect rule from `next` to `v3.5` (and remove the opposite redirect rule that was added via #326)
 3. **NOT** create another `/docs/next` folder until we have a need for it and/or until we've resolved what we'll be doing with #252, among other issues.

**Comment by lilic** [comment]
Could we also add moving all metrics, logs, etc under a new section just for Observability in the navigation as per suggestion in the https://github.com/etcd-io/website/issues/280#issuecomment-839537655. What do you think?

**Comment by nate-double-u** [comment]
@lilic, I think having a separate section for Observability in the navigation is a good idea. I'll open a separate issue so we can discuss where it should fit, and what needs to be moved into it. This would just be for `next`/`v3.5` and onward correct?

**Comment by nate-double-u** [comment]
Sorry for the noise, [New IA implementation #267](https://github.com/etcd-io/website/issues/267) is probably a better place to discuss  adding a new page/section for Observability.

**Comment by spzala** [comment]
@nate-double-u just fyi, I think we can take care of https://github.com/etcd-io/website/issues/377 under here. Thanks!

**Comment by nate-double-u** [comment]
Closing this issue as the remaining part of it (Adding etcdutl documentation #309) can be handled as a standalone issue -- congrats on the release everyone.
