### ISSUE TITLE
API reference: typo in front matter and more

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#330]
This is in follow up to #329. Here are the changes that still need to be done (IMHO):

- [x] Disclaimer: (#337)
  - [ ] Fix typo: drop the "a" in "This is a generated ..."
  - [x] Leave the disclaimer in the page body.
  - [x] Actually, I think that the following disclaimer text would be better. WDYT?
     > This API reference is autogenerated from the named `.proto` files.
- [x] Titles: the entire website is about etcd, so I suggest dropping 'etcd' from the titles, fix capitalization, etc., so that they become: (#337)
  - [x] **API reference**
  - [x] **API reference: concurrency**
- [x] Drop the weights (#337)
- [x] Fix upstream script https://github.com/etcd-io/etcd/blob/main/scripts/genproto.sh -- see https://github.com/etcd-io/etcd/issues/13050. ([#13062](https://github.com/etcd-io/etcd/pull/13062))

**Comment by nate-double-u** [comment]
Fixed in https://github.com/etcd-io/etcd/pull/13062
