### ISSUE TITLE
New top-nav (for matching new IA)

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#341]
This is a companion issue to _New IA implementation_ #267.

- [x] _Docs_ (/docs/latest)
- [x] Blog (/blog)
- [x] Community (/community) #306 #313
- [x] Install (/docs/latest/install) #318
- [x] Play, [play.etcd.io/play](http://play.etcd.io/play) #342, #343
- [x] _Versions_, only active for pages under `/docs` - #338
- ~~Quickstart (/docs/latest/quickstart)~~

**Comment by chalin** [comment]
Thanks for the PRs @nate-double-u. All done!
